#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Hermes Agent — Railway Entrypoint
#
# On first boot:  validates env vars, creates config.yaml + .env, marks init
# On subsequent:  reuses existing config from the persistent volume
#
# Required env vars (set in Railway dashboard):
#   - At least ONE provider key (OPENROUTER_API_KEY, ANTHROPIC_API_KEY, or OPENAI_API_KEY)
#   - At least ONE platform token (TELEGRAM_BOT_TOKEN, DISCORD_BOT_TOKEN, or SLACK_BOT_TOKEN)
#
# Optional env vars:
#   - HERMES_MODEL           (default: anthropic/claude-sonnet-4)
#   - TELEGRAM_ALLOWED_USERS (comma-separated Telegram user IDs)
#   - DISCORD_ALLOWED_USERS  (comma-separated Discord user IDs)
#   - SLACK_ALLOWED_USERS    (comma-separated Slack user IDs)
#   - TERMINAL_BACKEND       (default: local)
# ============================================================================

HERMES_HOME="${HERMES_HOME:-/data/.hermes}"
WORKSPACE="${MESSAGING_CWD:-/data/workspace}"
INIT_MARKER="${HERMES_HOME}/.initialized"

echo "╔══════════════════════════════════════════╗"
echo "║   Hermes Agent — Railway Bootstrap       ║"
echo "╚══════════════════════════════════════════╝"

# ── Create directory structure ──────────────────────────────────────────────
mkdir -p "${HERMES_HOME}"/{cron,sessions,logs,memories,skills,pairing,hooks,image_cache,audio_cache}
mkdir -p "${WORKSPACE}"

# ── Validate: need at least one provider ────────────────────────────────────
PROVIDER_FOUND=false
for var in OPENROUTER_API_KEY ANTHROPIC_API_KEY OPENAI_API_KEY; do
  if [ -n "${!var:-}" ]; then
    PROVIDER_FOUND=true
    break
  fi
done

if [ "$PROVIDER_FOUND" = false ]; then
  echo "ERROR: No LLM provider key found."
  echo "Set at least one of: OPENROUTER_API_KEY, ANTHROPIC_API_KEY, OPENAI_API_KEY"
  exit 1
fi

# ── Validate: need at least one messaging platform ──────────────────────────
PLATFORM_FOUND=false
for var in TELEGRAM_BOT_TOKEN DISCORD_BOT_TOKEN SLACK_BOT_TOKEN; do
  if [ -n "${!var:-}" ]; then
    PLATFORM_FOUND=true
    break
  fi
done

if [ "$PLATFORM_FOUND" = false ]; then
  echo "ERROR: No messaging platform token found."
  echo "Set at least one of: TELEGRAM_BOT_TOKEN, DISCORD_BOT_TOKEN, SLACK_BOT_TOKEN"
  exit 1
fi

# ── Write .env (always refresh from Railway vars) ───────────────────────────
echo "→ Writing ${HERMES_HOME}/.env"
cat > "${HERMES_HOME}/.env" <<ENVEOF
# Auto-generated by Railway entrypoint — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Provider keys
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}

# Telegram
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}

# Discord
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-}
DISCORD_ALLOWED_USERS=${DISCORD_ALLOWED_USERS:-}

# Slack
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
SLACK_ALLOWED_USERS=${SLACK_ALLOWED_USERS:-}
ENVEOF

# ── Generate config.yaml on first boot only ─────────────────────────────────
if [ ! -f "${INIT_MARKER}" ]; then
  echo "→ First boot detected — generating config.yaml"

  # Determine default model based on which provider key is set
  if [ -n "${HERMES_MODEL:-}" ]; then
    MODEL="${HERMES_MODEL}"
  elif [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    MODEL="anthropic/claude-sonnet-4"
  elif [ -n "${OPENROUTER_API_KEY:-}" ]; then
    MODEL="openrouter/anthropic/claude-sonnet-4"
  elif [ -n "${OPENAI_API_KEY:-}" ]; then
    MODEL="openai/gpt-4o"
  else
    MODEL="anthropic/claude-sonnet-4"
  fi

  TERMINAL="${TERMINAL_BACKEND:-local}"

  # Build platforms list
  PLATFORMS=""
  [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && PLATFORMS="${PLATFORMS}\n  - telegram"
  [ -n "${DISCORD_BOT_TOKEN:-}" ]  && PLATFORMS="${PLATFORMS}\n  - discord"
  [ -n "${SLACK_BOT_TOKEN:-}" ]    && PLATFORMS="${PLATFORMS}\n  - slack"

  cat > "${HERMES_HOME}/config.yaml" <<CFGEOF
# Hermes Agent config — generated by Railway entrypoint
# Edit this file directly on the volume, or redeploy to regenerate

model: "${MODEL}"

terminal:
  backend: ${TERMINAL}
  cwd: "${WORKSPACE}"
  timeout: 180

gateway:
  platforms:$(echo -e "${PLATFORMS}")

display:
  skin: default

memory:
  enabled: true

skills:
  enabled: true
CFGEOF

  echo "→ Config written with model=${MODEL}, terminal=${TERMINAL}"

  # Mark as initialized so we don't overwrite config on next deploy
  touch "${INIT_MARKER}"
  echo "✓ First-boot initialization complete"
else
  echo "✓ Existing config found — reusing (delete ${INIT_MARKER} to regenerate)"
fi

# ── Launch ──────────────────────────────────────────────────────────────────
echo ""
echo "→ Starting Hermes gateway..."
echo "  HERMES_HOME=${HERMES_HOME}"
echo "  Workspace=${WORKSPACE}"
echo ""

# Always sync model from env var if set
if [ -n "${HERMES_MODEL:-}" ]; then
  sed -i "s|^model:.*|model: \"${HERMES_MODEL}\"|" "${HERMES_HOME}/config.yaml"
fi

exec hermes gateway
